# Generated by Django 3.0.5 on 2020-08-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='item',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.CharField(default='DEBIT', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='store_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
