# Generated by Django 3.0.5 on 2020-08-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('banner', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='cardnumber',
            field=models.CharField(default='XXXXXXXXX', max_length=19),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
