# Generated by Django 3.0.5 on 2020-08-11 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(default='Product descriptions')),
                ('thumbnail', models.CharField(max_length=255)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('store_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Store')),
            ],
        ),
    ]
