# Generated by Django 3.0.5 on 2020-08-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=32)),
                ('date_add', models.DateTimeField(verbose_name='date add in database')),
                ('product_quantity', models.IntegerField(verbose_name='availabale in storage')),
                ('thumbnail_id', models.CharField(max_length=32)),
            ],
        ),
    ]
