# Generated by Django 3.0.5 on 2020-08-03 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail_id',
            new_name='thumbnail_file',
        ),
    ]
